### ISSUE TITLE
Milestone 1 checklist

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/525-group23#1]
- [x] [1. Team-work contract](https://github.com/UBC-MDS/525-group23/issues/2)
- [x] [2. Creating repository and project structure](https://github.com/UBC-MDS/525-group23/issues/3)
- [x] [3. Downloading the data](https://github.com/UBC-MDS/525-group23/issues/4)
- [x] [4. Combining data CSVs](https://github.com/UBC-MDS/525-group23/issues/5)
- [x] [5. Load the combined CSV to memory and perform a simple EDA](https://github.com/UBC-MDS/525-group23/issues/6)
- [x] [6. Perform a simple EDA in R](https://github.com/UBC-MDS/525-group23/issues/7)

**Comment by fatse** [comment]
Closing this as it has been addressed.
