### ISSUE TITLE
Milestone 3 checklist

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/525-group23#25]
- [x] [1. Setup your EMR cluster with Spark & JupyterHub](https://github.com/UBC-MDS/525-group23/issues/26).
- [x] [2. Setup your WebBrowser(Firefox) for EMR](https://github.com/UBC-MDS/525-group23/issues/27).
- [x] [3. Develop a ML model using scikit-learn. (We will be using this model to deploy for our next milestone.)](https://github.com/UBC-MDS/525-group23/issues/28)
- [x] [4. Obtain best hyperparameter settings using spark's MLlib](https://github.com/UBC-MDS/525-group23/issues/29).
