### ISSUE TITLE
Milestone 4 checklist

### ISSUE THREAD

**Issue by fatse** [UBC-MDS/525-group23#33]
- [x] [1. Develop your API](https://github.com/UBC-MDS/525-group23/issues/34)
- [x] [2. Deploy your API](https://github.com/UBC-MDS/525-group23/issues/35)
- [x] [3. Summarize your journey from Milestone 1 to Milestone 4](https://github.com/UBC-MDS/525-group23/issues/36)
- [x] [4. Submission instructions](https://github.com/UBC-MDS/525-group23/issues/37)
